site_name: "DOCS"
site_description: "Documentação para desenvolvimento de software."
site_url: "https://ucsal.github.io/docs"
repo_url: https://github.com/ucsal/docs
repo_name: docs
edit_uri: edit/main/docs/
theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.instant
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
    - diagrams # <- ativa suporte mais amplo


plugins:
  - search
  - privacy
  - social
  # - optimize
  #- git-revision-date-localized:
  #    locale: pt_BR
  #    fallback_to_build_date: true
  #- git-authors
  - minify
  #- awesome-pages
  #- mermaid2
  #- glightbox

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pooadoc/pooadoc.github.io
      name: GitHub Site
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mariojpereira/
      name: LinkedIn
    - icon: simple/orcid
      link: https://orcid.org/0009-0003-2882-6728
      name: ORCID
    - icon: fontawesome/brands/github
      link: https://github.com/mariojp
      name: GitHub Pessoal


  consent:
    title: "Consentimento de cookies"
    description: >-
      Usamos cookies para lembrar suas preferências e medir a eficácia do
      material. Com o seu consentimento, ajudará a tornar nossa documentação
      melhor.
    # quais botões mostrar (ordem importa)
    actions:
      - accept
      - reject
      - manage
    cookies:
      analytics:
        name: "Métricas (Google Analytics)"
        checked: true     # começa desativado
      github:
        name: "Integração GitHub (estrelas/releases)"
        checked: true
  analytics:
    provider: google
    property: G-3LD8DRX1HZ   # substitua pelo seu ID de medição do Google Analytics


markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - meta

copyright: >
  © 2025 POOA — <a href="#__consent">cookies</a>


nav:
  - INÍCIO: index.md
#  - SOLID:
#      - solid/index.md
#      - SRP: solid/srp.md
#      - OCP: solid/ocp.md
#      - LSP: solid/lsp.md
#      - ISP: solid/isp.md
#      - DIP: solid/dip.md
#  - GOF: gof/index.md
  - METODOLOGIAS: 
    - metodologias/pushpull.md
  - GUIAS: 
    - guias/index.md
    - GIT GITHUB: guias/git-github.md
    - JAVA JDK: guias/jdk.md
    - Tomcat: guias/tomcat.md
#    - Maven: guias/tomcat.md
#    - JUnit: guias/tomcat.md
extra_css:
  - css/extra.css
